#spring:
#  redis:
#    host:127.0.0.1
#    database:0
#    port:6379
spring:
  datasource:
    url: jdbc:mysql://restbook0.c0w9alt8cqnn.ap-southeast-2.rds.amazonaws.com:3306/restbook
    username: "zql20000924"
    password: "1q2w3e4r5t"
    driver-class-name: com.mysql.cj.jdbc.Driver
#    GRANT ALL PRIVILEGES ON *.* TO 'b08eacd0f48eea'@'%' IDENTIFIED BY '18556bdc77e5aaf';
